language: python

python:
  - '3.6'

script:
  - pip install .
  - pytest -vvv

deploy:
  provider: pypi
  user: "arrrlo"
  password:
    secure: "P045EEoo5LakV3F1LbwlD+QomGmo5d7zwr1VAib2L8O/gGJJQc7kKHfTcjlpGxiaFvUUq1z1MKfd6auPx587aGJDEGLN1pQSzs0FZaRhqKzRCKy1FUjbYEna8bqVDRgyJaSZ3kjabCUVezmLeK/N67idC6eJalmCWlBztjWJEyH/yr+2xy7o9khK4oENmSyL0X5uRY30Ull770ayinZYTPw8LV/R6JVNF6Ow9yIookCvr1j9EGGi7IbtTLRuBdxlH/jfrrIkBxbNRXNqgsu0krfbkM4GhysseL8yvhbLqVAIO1ulqq8OTql666cFTc3xaUiWxUYLLPx9FVMx33gKIggCquLSXGh/vw+svhWVon6fB6iVbHRyfIezwEJpUMsCBr6BXCvTZliBgnOTj6m04/CrJbN4khF3qX4ipwMVfsXkbjwHOtDu6zZ+llFrqK1Kzk3qfdOT0pJWghFMeFMW1CgTLOroBSDMNdEyiJeqM4NbijkO4kO4kPWOdBTACkFUrFMxvu3QSJ4unWAguAIX1RUWXhZxWAV8TTLzsi/8LubfFqBHbSc7gG0NtgSiJ4EM4tuNBwQ4+PE1KLfBAg1cSwUsCsL1OygxADRDQQPg1X7IZGzXxbbLQ3R0VVvpQBKmu0njhJf8iXk3ucvcKnZ/Q9RYbonO/SzX5J1EREg4YhU="
  on:
    branch: master
