language: python

python:
  - '3.6'

script:
  - pip install .
  - pytest -vvv

deploy:
  provider: pypi
  user: "arrrlo"
  password:
    secure: "SZZlMFq8Msbfc9BNZ41m9ZcVxUiPUORicIf2hjbBU7HBSd28s3zmfuZphGe6FfBQLvc+nf36x+ZUeXx12miLkmhd3NCkLuOu5Wa9BH7C2T6XJCJ35kNDBi/TPUPApmxAFxQ3z+FmKGINiVcX35rhvF6QHbNQYA97xCZZGdcnO0D5/g2DaNmUq2xJbyb1dr+0Ay8gpnRFkNxxZsH/CR4vXRgnDazqk5daYzsJJJ6czsBUfSJJfc0wB2N/3eYoAtfNusyzy401AlOa/t1EzpDW3BSF/RCC27lu3gUhryYNCBTIPXZmasEH13vTNHANXTRUpNFOwCJZPtThB5i/P+tAvn7/70K1Ud/wXvyvMEMn4Ltl38jhwX27SJcDoqHPHrMaQUrANOjHxVx/jYqukZp698ES10jjhPXSM45v4kLmMaqJTRDSfefSM/pZzaSdSmttJp0sqtT+YBW+cIo10myu6qf+MyXXzAcEvQ9dF+kPf9606ANqZni3OggUF+bl3jSeUdoNMnDxyrjtqbOMApeHwNfMhCAa3veggsIDBnjQ3Qfeln2RXt3IrVQJLIRz5bxb5hrPJ0pysVbuME5MVgitFPxCnTGhkUqogsO0kRBYHCAt1Qu5uyNh+hgHUpcfPP8Zy+pMtF9gf0Bkccjel6l38KKEKJRkiPTXP/crx/fopbU="
  on:
    branch: master
