language: python

python:
  - '3.6'

script:
  - pip install .
  - pytest -vvv

deploy:
  provider: pypi
  user: "arrrlo"
  password:
    secure: "Fwf5jVwBYXoindurwtxy0kDu+LZRki1tSOZqrTIJ5vRoS+nwUniu5mK/gQKYHSicCntsN7hX84LWxul6u0IWslmEk5/YIPB6383qG+Y8kDrTY1f70AeO3xcH/bAtCZ//1Hz1dMXzhNOC/w3gZlsDdnvCN0tcYZQewDkWI7u/mm7FnmcshpA9taRP1gOPTvkqYdZdKHNGw96UIOS8d63nlA9O8UVSf2lTGmdK+jnN5U2pnSr3PQ4A2xt6VPJOAZj4ourZ+Xf/N9CardXKVr3jx8TV+CsIJmVL1Lf9uCdHn1fD7ABITYOP5DCog4OZkoQgBK7nkmwqhFKv/7xuZsrKLhSs/j8CaTLADyVNBY4YnfPQlaD46/YPL0m63Wt6PdacadBTiBVBC3yg0/EeqSfEuC43io/h83JJw18AKrGh1IzEGvoaFqKd09781L0AqtTPM448zuDOJQV9jVgJBqycHARS2neprHzWmESbtOBqKfRR/IOCsdjAOl+uQ+tUKpEO7auXAbPykmbEy067y4+Qbcyfh5ywKHGoz6v1aean1+aJtT4W9Tnykp37DEKXxdCkdI81P3DnKPrrHF5kDq0jCLaYB6P5pj3WugTNOxmewzTo/HaHyacftp3N/DCO6TWHe1wTfDqPz/AJQfk0fcrM1AZMYYdCb48KvF9gc9CHu/o="
  on:
    branch: master
