language: python

python:
  - '3.6'

script:
  - pip install .
  - pytest -vvv

deploy:
  provider: pypi
  user: "arrrlo"
  password:
    secure: "AqWzXFE2ut3drPFtt/MYAbjjcmupTXfbX6QYLdKBUHw2dSaddgWuU8TDp3sCgo8JcNJeqAoCQxVaK0uwfpDbRONjk0tH0sGMEJX2QFmUon/uOpWsnx4HbBGHxumfvp9ud0PyK4hNxg2IHBUcAcO6gfhV3bKu9HhOjL2GRoj1f9QQrnxEJzGMewIDG+Vf1dHgabW+dJaaEum0J6+sg5LeN1qE0H4Lcs9/dE26dmDz7f0t+0rdlTsP+2+e/sfw3JF63fUQmNE/f51wUi4k4QxS7L3mB7WnCkXJVBztegInttcFytMx51OTnf4jixTrDmdJD2i8hdLhHEi0uyYtDKFCA34mMLuV//ZiCJaZcM3rsTEZM8c1c5AcTv5yeAZV1ezb6xBOpv4qKrOpdfEjQXBfMpRizxO9n5SQdzVR/lOK6d3MGAu9DqowTy2wKEWReHKpNDJxQsbBjo2ReLqM+lZu+Ckefq/KzKLUMuotvMI0hwr1rzlb7qUKa5Ea4PFVMqBW+JmBkhOllXlR7SVor4+OPTFZBrKVQRHj9pX1yuaXYgEC4XJ0yVwBfDhqGyv/IBfgzHgRiXGuRldumS+vB5AkarUZ3GKvlgfr28/hwBgkriCMOTJIUyNPG7Jf8K8qtogPxq69plmp/IVCxFiPt9arsTxgwvTuKt7vfLD/py8nJww="
  on:
    branch: master
